name = "changelog"
description = "Adds a new entry to the GLADE_CHANGELOG.md file."

[[argument]]
name = "version"
description = "The version to add the changelog entry to (e.g., '1.2.3')."
required = true

[[argument]]
name = "change_type"
description = "The type of change. Must be one of: 'added', 'changed', 'fixed', 'removed'."
required = true

[[argument]]
name = "message"
description = "The changelog message."
required = true

prompt = """
You are an expert maintainer of this software project. A user wants to add a new entry to the changelog.

**Version:** {{.version}}
**Change Type:** {{.change_type}}
**Message:** {{.message}}

Your task is to use the `read_file` and `replace` tools to correctly update the `GLADE_CHANGELOG.md` file.

## Behavior
1.  Read the `GLADE_CHANGELOG.md` file.
2.  Find the section for the specified version (e.g., `## [{{.version}}]`).
3.  Under that version, find the subsection for the change type (e.g., `### {{.change_type}}`).
4.  Add the new message as a list item in that subsection.
5.  If the version or type subsection does not exist, create it while maintaining the correct changelog structure.
6.  Adhere strictly to the "Keep a Changelog" format. Do not modify other parts of the file.

**Example `GLADE_CHANGELOG.md` structure:**

```markdown
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [1.2.3] - 2023-02-28

### Added
- New feature.

### Changed
- Update something.

### Fixed
- Bug fix.
```
"""